##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################

SDEV=../test
TAINTS_LIB=taints
TAINTS_OBJ=$(OBJDIR)
TAINTS_INTERFACE=taint_interface
REPLAY_LIB += $(SDEV)/libutil.a 
TOOL_LIBS += $(SDEV)/libutil.a
TOOL_CXXFLAGS += -I$(SDEV) -g
#TOOL_CXXFLAGS += -I$(SDEV) -DDEBUGTRACE=0x201e42 -DDEBUGTRACE_OUTPUT=0xcc1f
#TOOL_CXXFLAGS += -I$(SDEV) -DDEBUGTRACE=0x201e42 -DDEBUGTRACE_OUTPUT=0x0000
GLIB_INCLUDES=-I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include
GLIB_LIB= -lglib-2.0
TOOL_CXXFLAGS += $(GLIB_INCLUDES) -I$(SDEV)
TAINT_BACK_OBJS=$(TAINTS_OBJ)taint_full_interface$(OBJ_SUFFIX) $(TAINTS_OBJ)taint_byte_creation$(OBJ_SUFFIX) $(TAINTS_OBJ)maputil$(OBJ_SUFFIX) $(TAINTS_OBJ)mmap_regions$(OBJ_SUFFIX) 
TAINT_OBJS=$(OBJDIR)xray_token$(OBJ_SUFFIX) $(OBJDIR)xray_slab_alloc$(OBJ_SUFFIX) $(OBJDIR)recheck_log$(OBJ_SUFFIX) $(SDEV)/parseklib$(OBJ_SUFFIX) 
APP_CC=gcc

##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := linkage_offset print_bb ctrl_flow_bb_trace data_flow_ndx

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS :=

# This defines a list of tests that should run in the "short" sanity. Tests in this list must also
# appear either in the TEST_TOOL_ROOTS or the TEST_ROOTS list.
# If the entire directory should be tested in sanity, assign TEST_TOOL_ROOTS and TEST_ROOTS to the
# SANITY_SUBSET variable in the tests section below (see example in makefile.rules.tmpl).
SANITY_SUBSET :=

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS :=

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS := postprocess_linkage parse_outputs showall

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS := xray_token \
		taint_byte_creation \
		taint_full_interface \
		xray_slab_alloc \
		maputil \
                mmap_regions \
		recheck_log 

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS :=


##############################################################
#
# Test recipes
#
##############################################################

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test


##############################################################
#
# Build rules
#
##############################################################
$(OBJDIR)xray_token$(OBJ_SUFFIX): xray_token.h xray_token.c
	$(APP_CC) -Wall -Werror -O2 -c -o $(OBJDIR)xray_token$(OBJ_SUFFIX) $(GLIB_INCLUDES) xray_token.c

$(OBJDIR)maputil$(OBJ_SUFFIX): maputil.h maputil.c
	$(CXX) $(TOOL_CXXFLAGS) -Wall -Werror -O2 -c -o $(OBJDIR)maputil$(OBJ_SUFFIX) $(GLIB_INCLUDES) maputil.c

$(OBJDIR)postprocess_linkage: xray_slab_alloc.h postprocess_linkage.cpp $(OBJDIR)xray_token$(OBJ_SUFFIX) maputil.c maputil.h
	$(CXX) -std=c++0x $(TOOL_CXXFLAGS) -Wall -Werror -O2 -o $(OBJDIR)postprocess_linkage $(GLIB_INCLUDES) $(OBJDIR)xray_token$(OBJ_SUFFIX) postprocess_linkage.cpp maputil.c -lglib-2.0 -lrt

$(OBJDIR)parse_outputs: xray_slab_alloc.h parse_outputs.c $(OBJDIR)xray_token$(OBJ_SUFFIX) maputil.c maputil.h
	$(APP_CC) $(TOOL_CXXFLAGS) -Wall -Werror -O2 -o $(OBJDIR)parse_outputs $(GLIB_INCLUDES) $(OBJDIR)xray_token$(OBJ_SUFFIX) parse_outputs.c maputil.c -lglib-2.0 -lrt

$(OBJDIR)showall: showall.c maputil.c maputil.h
	$(APP_CC) -Wall -Werror -g -o $(OBJDIR)showall $(GLIB_INCLUDES) showall.c maputil.c -lglib-2.0

$(OBJDIR)xray_slab_alloc$(OBJ_SUFFIX): xray_slab_alloc.h xray_slab_alloc.c
	$(APP_CC) -Wall -Werror -O2 -c -o $(OBJDIR)xray_slab_alloc$(OBJ_SUFFIX) xray_slab_alloc.c

$(OBJDIR)taint_byte_creation$(OBJ_SUFFIX): $(TAINTS_INTERFACE)/taint_byte_creation.c $(TAINTS_INTERFACE)/taint_creation.h taint_nw.h
	$(CXX) $(TOOL_CXXFLAGS) -Wall -Werror -O2 -c -o $(TAINTS_OBJ)taint_byte_creation$(OBJ_SUFFIX) $(GLIB_INCLUDES) $(TAINTS_INTERFACE)/taint_byte_creation.c

$(OBJDIR)mmap_regions$(OBJ_SUFFIX): mmap_regions.h mmap_regions.cpp linkage_common.h
	$(CXX) $(TOOL_CXXFLAGS) -std=c++0x -Wall -Werror -O2 -c -o $(TAINTS_OBJ)mmap_regions$(OBJ_SUFFIX) $(GLIB_INCLUDES) mmap_regions.cpp 

$(OBJDIR)taint_full_interface$(OBJ_SUFFIX): $(TAINTS_INTERFACE)/taint_full_interface.c $(TAINTS_INTERFACE)/taint_interface.h taint_nw.h mmap_regions.h mmap_regions.cpp linkage_common.h
	$(CXX) $(TOOL_CXXFLAGS) -std=c++0x -Wall -Werror -O2 -c -o $(TAINTS_OBJ)taint_full_interface$(OBJ_SUFFIX) $(GLIB_INCLUDES) $(TAINTS_INTERFACE)/taint_full_interface.c 

$(OBJDIR)linkage_new2$(OBJ_SUFFIX): linkage_new2.cpp xray_slab_alloc.c xray_slab_alloc.h mmap_regions.h mmap_regions.cpp $(TAINTS_INTERFACE)/taint_interface.h $(TAINTS_INTERFACE)/taint_full_interface.c $(TAINTS_INTERFACE)/taint_byte_creation.c taint_nw.h linkage_common.h
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)linkage_new2$(PINTOOL_SUFFIX): $(OBJDIR)linkage_new2$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(MY_OBJS) $(TAINT_BACK_OBJS) $(TAINT_OBJS) -lglib-2.0

# DATA TOOL only for debugging 
$(OBJDIR)linkage_data$(OBJ_SUFFIX): linkage_new2.cpp recheck_log.cpp xray_slab_alloc.c xray_slab_alloc.h $(TAINTS_INTERFACE)/taint_interface.h $(TAINTS_INTERFACE)/taint_full_interface.c $(TAINTS_INTERFACE)/taint_byte_creation.c splice.c maputil.c
	$(CXX) -DLINKAGE_DATA -DCTRL_FLOW $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $< 

$(OBJDIR)linkage_data$(PINTOOL_SUFFIX): $(OBJDIR)linkage_data$(OBJ_SUFFIX) 
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(MY_OBJS) $(TAINT_BACK_OBJS) $(TAINT_OBJS) -lglib-2.0 -lrt

# DATA+INDEX TOOL
$(OBJDIR)linkage_offset$(OBJ_SUFFIX): linkage_new2.cpp recheck_log.cpp xray_slab_alloc.c xray_slab_alloc.h $(TAINTS_INTERFACE)/taint_interface.h $(TAINTS_INTERFACE)/taint_full_interface.c $(TAINTS_INTERFACE)/taint_byte_creation.c splice.c maputil.c mmap_regions.h mmap_regions.cpp linkage_common.h
	$(CXX) -DLINKAGE_DATA_OFFSET -DCTRL_FLOW $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)linkage_offset$(PINTOOL_SUFFIX): $(OBJDIR)linkage_offset$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(MY_OBJS) $(TAINT_BACK_OBJS) $(TAINT_OBJS) -lglib-2.0 -lrt

# BASIC BLOCK PRINTER
$(OBJDIR)print_bb$(OBJ_SUFFIX): print_bb.cpp 
	$(CXX) -DLINKAGE_DATA_OFFSET -DCTRL_FLOW $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)print_bb$(PINTOOL_SUFFIX): $(OBJDIR)print_bb$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(MY_OBJS)

$(OBJDIR)ctrl_flow_bb_trace$(OBJ_SUFFIX): ctrl_flow_bb_trace.cpp 
	$(CXX) -DLINKAGE_DATA_OFFSET -DCTRL_FLOW $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)ctrl_flow_bb_trace$(PINTOOL_SUFFIX): $(OBJDIR)ctrl_flow_bb_trace$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(MY_OBJS)

$(OBJDIR)data_flow_ndx$(OBJ_SUFFIX): data_flow_ndx.cpp 
	$(CXX) -std=c++0x -DLINKAGE_DATA_OFFSET -DCTRL_FLOW $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)data_flow_ndx$(PINTOOL_SUFFIX): $(OBJDIR)data_flow_ndx$(OBJ_SUFFIX) $(OBJDIR)mmap_regions$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(MY_OBJS)


