asm (
".section	.text\n"
".globl _section1\n"
"_section1:\n"
"mov ecx, 17\n"
"mov dword ptr [0xbffff38c], ecx\n"
"call handle_index_diverge\n"
"mov edx, 576\n"
"add eax, edx\n"
"mov eax, 5\n"
"mov edx, eax\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov edx, 9\n"
"call handle_index_diverge\n"
);
