asm (
".section	.text\n"
".globl _section1\n"
"_section1:\n"
"pushfd\n"
"call recheck_wait_init\n"
"popfd\n"
"call access_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8d7c], edx\n"
"mov dword ptr [0x8bd8d80], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"call stat64_recheck\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"ret\n"
"call jump_diverge:\n"
"push eax\n"
"push ecx\n"
"push edx\n"
"call handle_jump_diverge\n"
"call index_diverge:\n"
"push eax\n"
"push ecx\n"
"push edx\n"
"call handle_index_diverge\n"
);
