asm (
".section	.text\n"
".globl _section1\n"
"_section1:\n"
"pushfd\n"
"call recheck_wait_init\n"
"popfd\n"
"call access_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call fstat64_recheck\n"
"mov esi, dword ptr [0xbfffeeb8]\n"
"mov ecx, dword ptr [0xbfffeebc]\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov  dword ptr [0xbfffedb0], esi\n"
"mov dword ptr [0xbfffed64], esi\n"
"mov esi, dword ptr [0xbfffed64]\n"
"mov esi,  dword ptr [0xbfffedb0]\n"
"call close_recheck\n"
"mov edx, dword ptr [0xbfffeebc]\n"
"mov eax, dword ptr [0xbfffeeb8]\n"
"mov dword ptr [0xb7fdde4c], edx\n"
"mov dword ptr [0xb7fdde48], eax\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call fstat64_recheck\n"
"mov esi, dword ptr [0xbfffee98]\n"
"mov ecx, dword ptr [0xbfffee9c]\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fdde4c]\n"
"mov eax, dword ptr [0xb7fdde48]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov  dword ptr [0xbfffed90], esi\n"
"mov dword ptr [0xbfffed44], esi\n"
"mov esi, dword ptr [0xbfffed44]\n"
"mov esi,  dword ptr [0xbfffed90]\n"
"call close_recheck\n"
"mov edx, dword ptr [0xbfffee9c]\n"
"mov eax, dword ptr [0xbfffee98]\n"
"mov dword ptr [0xb7fc51e4], edx\n"
"mov dword ptr [0xb7fc51e0], eax\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call fstat64_recheck\n"
"mov esi, dword ptr [0xbfffee78]\n"
"mov ecx, dword ptr [0xbfffee7c]\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fdde4c]\n"
"mov eax, dword ptr [0xb7fdde48]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc51e4]\n"
"mov eax, dword ptr [0xb7fc51e0]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov  dword ptr [0xbfffed70], esi\n"
"mov dword ptr [0xbfffed24], esi\n"
"mov esi, dword ptr [0xbfffed24]\n"
"mov esi,  dword ptr [0xbfffed70]\n"
"call close_recheck\n"
"mov edx, dword ptr [0xbfffee7c]\n"
"mov eax, dword ptr [0xbfffee78]\n"
"mov dword ptr [0xb7fc54b4], edx\n"
"mov dword ptr [0xb7fc54b0], eax\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call fstat64_recheck\n"
"mov esi, dword ptr [0xbfffee58]\n"
"mov ecx, dword ptr [0xbfffee5c]\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fdde4c]\n"
"mov eax, dword ptr [0xb7fdde48]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc51e4]\n"
"mov eax, dword ptr [0xb7fc51e0]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc54b4]\n"
"mov eax, dword ptr [0xb7fc54b0]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov  dword ptr [0xbfffed50], esi\n"
"mov dword ptr [0xbfffed04], esi\n"
"mov esi, dword ptr [0xbfffed04]\n"
"mov esi,  dword ptr [0xbfffed50]\n"
"call close_recheck\n"
"mov edx, dword ptr [0xbfffee5c]\n"
"mov eax, dword ptr [0xbfffee58]\n"
"mov dword ptr [0xb7fc579c], edx\n"
"mov dword ptr [0xb7fc5798], eax\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call fstat64_recheck\n"
"mov esi, dword ptr [0xbfffee38]\n"
"mov ecx, dword ptr [0xbfffee3c]\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fdde4c]\n"
"mov eax, dword ptr [0xb7fdde48]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc51e4]\n"
"mov eax, dword ptr [0xb7fc51e0]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc54b4]\n"
"mov eax, dword ptr [0xb7fc54b0]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc579c]\n"
"mov eax, dword ptr [0xb7fc5798]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov  dword ptr [0xbfffed30], esi\n"
"mov dword ptr [0xbfffece4], esi\n"
"mov esi, dword ptr [0xbfffece4]\n"
"mov esi,  dword ptr [0xbfffed30]\n"
"call close_recheck\n"
"mov edx, dword ptr [0xbfffee3c]\n"
"mov eax, dword ptr [0xbfffee38]\n"
"mov dword ptr [0xb7fc5a74], edx\n"
"mov dword ptr [0xb7fc5a70], eax\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call fstat64_recheck\n"
"mov esi, dword ptr [0xbfffee18]\n"
"mov ecx, dword ptr [0xbfffee1c]\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, 0\n"
"xor edx, ecx\n"
"mov eax, 0\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fdde4c]\n"
"mov eax, dword ptr [0xb7fdde48]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc51e4]\n"
"mov eax, dword ptr [0xb7fc51e0]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc54b4]\n"
"mov eax, dword ptr [0xb7fc54b0]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc579c]\n"
"mov eax, dword ptr [0xb7fc5798]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov edx, dword ptr [0xb7fc5a74]\n"
"mov eax, dword ptr [0xb7fc5a70]\n"
"xor edx, ecx\n"
"xor eax, esi\n"
"or edx, eax\n"
"jz jump_diverge\n"
"mov  dword ptr [0xbfffed10], esi\n"
"mov dword ptr [0xbfffecc4], esi\n"
"mov esi, dword ptr [0xbfffecc4]\n"
"mov esi,  dword ptr [0xbfffed10]\n"
"call close_recheck\n"
"mov edx, dword ptr [0xbfffee1c]\n"
"mov eax, dword ptr [0xbfffee18]\n"
"mov dword ptr [0xb7fc5d44], edx\n"
"mov dword ptr [0xb7fc5d40], eax\n"
"call prlimit64_recheck\n"
"call prlimit64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call rt_sigaction_recheck\n"
"call rt_sigaction_recheck\n"
"call rt_sigaction_recheck\n"
"call rt_sigaction_recheck\n"
"call rt_sigaction_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"call prlimit64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"call prlimit64_recheck\n"
"call prlimit64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"call prlimit64_recheck\n"
"call gettimeofday_recheck\n"
"mov ecx, dword ptr [0xbffff46c]\n"
"imul ebx, dword ptr [0xbffff468], 0x3e8\n"
"mov eax, ecx\n"
"mov edx, 274877907\n"
"imul edx\n"
"sar ecx, 0x1f\n"
"sar edx, 0x6\n"
"sub edx, ecx\n"
"add edx, ebx\n"
"mov dword ptr [0x8ba746c], edx\n"
"mov  dword ptr [0xbffff430], ebx\n"
"mov  dword ptr [0xbffff3f8], edx\n"
"mov  dword ptr [0xbffff3e4], ebx\n"
"mov ebx,  dword ptr [0xbffff3e4]\n"
"mov edx,  dword ptr [0xbffff3f8]\n"
"mov  dword ptr [0xbffff3fc], ebx\n"
"mov ebx,  dword ptr [0xbffff3fc]\n"
"mov  dword ptr [0xbffff3fc], ebx\n"
"mov ebx,  dword ptr [0xbffff3fc]\n"
"call access_recheck\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8c84], edx\n"
"mov dword ptr [0x8bd8c88], ecx\n"
"call stat64_recheck\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8d7c], edx\n"
"mov dword ptr [0x8bd8d80], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8dac], edx\n"
"mov dword ptr [0x8bd8db0], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8d80]\n"
"xor edx, dword ptr [0x8bd8d7c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"call stat64_recheck\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8ed4], edx\n"
"mov dword ptr [0x8bd8ed8], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8d80]\n"
"xor edx, dword ptr [0x8bd8d7c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8db0]\n"
"xor edx, dword ptr [0x8bd8dac]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8f1c], edx\n"
"mov dword ptr [0x8bd8f20], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8d80]\n"
"xor edx, dword ptr [0x8bd8d7c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8db0]\n"
"xor edx, dword ptr [0x8bd8dac]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8ed8]\n"
"xor edx, dword ptr [0x8bd8ed4]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8b54], edx\n"
"mov dword ptr [0x8bd8b58], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8d80]\n"
"xor edx, dword ptr [0x8bd8d7c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8db0]\n"
"xor edx, dword ptr [0x8bd8dac]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8ed8]\n"
"xor edx, dword ptr [0x8bd8ed4]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8f20]\n"
"xor edx, dword ptr [0x8bd8f1c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8b94], edx\n"
"mov dword ptr [0x8bd8b98], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8d80]\n"
"xor edx, dword ptr [0x8bd8d7c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8db0]\n"
"xor edx, dword ptr [0x8bd8dac]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8ed8]\n"
"xor edx, dword ptr [0x8bd8ed4]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8f20]\n"
"xor edx, dword ptr [0x8bd8f1c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8b58]\n"
"xor edx, dword ptr [0x8bd8b54]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"call stat64_recheck\n"
"mov edx, dword ptr [0xbffff388]\n"
"mov ecx, dword ptr [0xbffff38c]\n"
"mov dword ptr [0xbffff31c], edx\n"
"mov dword ptr [0xbffff320], ecx\n"
"mov dword ptr [0x8bd8bd4], edx\n"
"mov dword ptr [0x8bd8bd8], ecx\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8c88]\n"
"xor edx, dword ptr [0x8bd8c84]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8d80]\n"
"xor edx, dword ptr [0x8bd8d7c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8db0]\n"
"xor edx, dword ptr [0x8bd8dac]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8ed8]\n"
"xor edx, dword ptr [0x8bd8ed4]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8f20]\n"
"xor edx, dword ptr [0x8bd8f1c]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8b58]\n"
"xor edx, dword ptr [0x8bd8b54]\n"
"or ecx, edx\n"
"jz jump_diverge\n"
"mov ecx, dword ptr [0xbffff320]\n"
"mov edx, dword ptr [0xbffff31c]\n"
"xor ecx, dword ptr [0x8bd8b98]\n"
"xor edx, dword ptr [0x8bd8b94]\n"
"or ecx, edx\n"
"jnz jump_diverge\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"mov ebx,  dword ptr [0xbffff430]\n"
"mov  dword ptr [0xbffff42c], ebx\n"
"mov ebx,  dword ptr [0xbffff42c]\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"call stat64_recheck\n"
"call stat64_recheck\n"
"mov eax, dword ptr [0xbffff2e8]\n"
"mov edx, dword ptr [0xbffff2ec]\n"
"xor edx, dword ptr [0xbffff34c]\n"
"xor eax, dword ptr [0xbffff348]\n"
"or edx, eax\n"
"jnz jump_diverge\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call stat64_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"push edx\n"
"push ecx\n"
"call open_recheck\n"
"pop ecx\n"
"pop edx\n"
"call fstat64_recheck\n"
"push edx\n"
"call read_recheck\n"
"pop edx\n"
"call close_recheck\n"
"ret\n"
"jump_diverge:\n"
"push eax\n"
"push ecx\n"
"push edx\n"
"call handle_jump_diverge\n"
"index_diverge:\n"
"push eax\n"
"push ecx\n"
"push edx\n"
"call handle_index_diverge\n"
);
